# Generated by Django 6.0.2 on 2026-02-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category_image_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
